name = "SlateRegistry"
uuid = "019e0f08-741e-4356-9487-3a1cba3794af"
repo = "git@github.com:kahliburke/SlateRegistry.git"
description = "Kaimon Slate extension packages"

[packages]
037ed0f0-9d4a-4e15-a26b-b7623adf1440 = { name = "CesiumSlate", path = "C/CesiumSlate" }
06afbefc-9613-4bb7-bc4a-f7a72d2076db = { name = "StarRating", path = "S/StarRating" }
141e1fc3-13f6-4de8-b22a-97670e9194c6 = { name = "SlatePlotly", path = "S/SlatePlotly" }
16f7ad8c-d856-4500-a529-cf73ac8ee665 = { name = "VolumeRendering", path = "V/VolumeRendering" }
3407f95d-69fb-4d30-a5a8-720a6642c965 = { name = "GlobeSlate", path = "G/GlobeSlate" }
34dae1dd-9e9d-4399-81aa-9d72c5d23232 = { name = "SlateBench", path = "S/SlateBench" }
4293ad4b-9d1e-41b5-a698-562d6dfeffbe = { name = "SlateAssess", path = "S/SlateAssess" }
48bdd467-e615-4c42-bca2-e391cca8438c = { name = "SlateAFM", path = "S/SlateAFM" }
8b1dd0a1-40b8-40bb-ae57-fd8e602dd54e = { name = "MermaidSlate", path = "M/MermaidSlate" }
9172b072-6bcf-488b-b185-96c3319d1521 = { name = "BonitoSlate", path = "B/BonitoSlate" }
ef7371ef-5451-47cf-aa18-309fc01b1667 = { name = "VolumeRenderingSlate", path = "V/VolumeRenderingSlate" }
f4c9f34b-fa6a-4506-9309-e8c0bac809fa = { name = "GiacSlate", path = "G/GiacSlate" }
