name = "SlateRegistry"
uuid = "019e0f08-741e-4356-9487-3a1cba3794af"
repo = "git@github.com:kahliburke/SlateRegistry.git"
description = "Kaimon Slate and its extension packages"

[packages]
037ed0f0-9d4a-4e15-a26b-b7623adf1440 = { name = "CesiumSlate", path = "C/CesiumSlate" }
06afbefc-9613-4bb7-bc4a-f7a72d2076db = { name = "StarRating", path = "S/StarRating" }
141e1fc3-13f6-4de8-b22a-97670e9194c6 = { name = "SlatePlotly", path = "S/SlatePlotly" }
3407f95d-69fb-4d30-a5a8-720a6642c965 = { name = "GlobeSlate", path = "G/GlobeSlate" }
4293ad4b-9d1e-41b5-a698-562d6dfeffbe = { name = "SlateAssess", path = "S/SlateAssess" }
bc31d39e-4442-48fa-b9ae-1bd99fed63f7 = { name = "SlateExtensionsBase", path = "S/SlateExtensionsBase" }
f4c9f34b-fa6a-4506-9309-e8c0bac809fa = { name = "GiacSlate", path = "G/GiacSlate" }
f7b954f5-0334-4562-ac21-b005218ce1da = { name = "KaimonSlate", path = "K/KaimonSlate" }
