name = "SlateRegistry"
uuid = "019e0f08-741e-4356-9487-3a1cba3794af"
repo = "git@github.com:kahliburke/SlateRegistry.git"
description = "Kaimon Slate and its extension packages"

[packages]
141e1fc3-13f6-4de8-b22a-97670e9194c6 = { name = "SlatePlotly", path = "S/SlatePlotly" }
bc31d39e-4442-48fa-b9ae-1bd99fed63f7 = { name = "SlateExtensionsBase", path = "S/SlateExtensionsBase" }
